### PR TITLE
Fix/media bottom sheet

### LINKED ISSUE #396: fix bottom media action
Image
Image

### PR DESCRIPTION
**Pull request by baraa0abd**
image

image

- fix the media bottoms color (no more green or yellow colors in add to list and rate bottoms)
- fix the place of the movie poster (bottom padding)

### CODE REVIEW

File: presentation/src/main/java/com/madrid/presentation/component/movieActorBackground/MoviePosterDetailScreen.kt [hunk 1]
```diff
@@ -54,11 +54,10 @@ fun MoviePosterDetailScreen(
             } else {
                 Box(
                     modifier = Modifier
-                        .padding(bottom = 16.dp)
+                        .padding(top = 88.dp, bottom = 24.dp , start = 80.dp, end = 80.dp)
                         .size(width = 200.dp, height = 260.dp)
-                        .align(Alignment.BottomCenter)
```
Comment (ahmedhgabr) [inline presentation/src/main/java/com/madrid/presentation/component/movieActorBackground/MoviePosterDetailScreen.kt:59]: The image is shifted to the left. The padding didn't solve it.

**Review by ahmedhgabr — DISMISSED** [review]

**Comment by ahmedhgabr** [comment]
Please specify what this PR does. What's new for the watchlist?

**Review by yasserahmed10 — APPROVED** [review]

**Review by yasserahmed10 — APPROVED** [review]

File: presentation/src/main/java/com/madrid/presentation/component/movieActorBackground/MoviePosterDetailScreen.kt [hunk 2]
```diff
@@ -54,11 +54,10 @@ fun MoviePosterDetailScreen(
             } else {
                 Box(
                     modifier = Modifier
-                        .padding(bottom = 16.dp)
+                        .padding(top = 88.dp, bottom = 24.dp , start = 90.dp, end = 80.dp)
```
Comment (Alaakhaled101) [inline presentation/src/main/java/com/madrid/presentation/component/movieActorBackground/MoviePosterDetailScreen.kt]: the fixed padding in start and end is not correct it should be:
modifier = Modifier.align(Alignment.BottomCenter)
To ensure the card is in the middle while changing the screen width.

WhatsApp Image 2025-08-16 at 19 26 27_16238d55

**Review by Alaakhaled101 — APPROVED** [review]
