### PR TITLE
fix: fix movies cards in **similar movies** screen and show rating

### LINKED ISSUE #556: similar movie screen
- rating not shown
- cards sie issue

** it should **
Image

** it is **

Image

### PR DESCRIPTION
**Pull request by baraa0abd**
image

### CODE REVIEW

File: presentation/src/main/java/com/madrid/presentation/screens/detailsScreen/similarMedia/SeeAllSimilarMediaScreen.kt [hunk 1]
```diff
@@ -88,25 +91,16 @@ fun SeeAllSimilarMediaScreenContent(
             modifier = Modifier
                 .fillMaxSize()
                 .background(Theme.color.surfaces.surface)
-                .padding(horizontal = 6.dp),
+                .padding(horizontal = 12.dp),
```
Comment (ahmedhgabr) [inline presentation/src/main/java/com/madrid/presentation/screens/detailsScreen/similarMedia/SeeAllSimilarMediaScreen.kt]: Too much padding. Why is all the padding on the left?
😭😭 😭 😭 😭 😭 😭 
image

Comment (baraa0abd) [reply presentation/src/main/java/com/madrid/presentation/screens/detailsScreen/similarMedia/SeeAllSimilarMediaScreen.kt]: the problem with the img szie not the card (i'm gonna fix it)

Comment (baraa0abd) [reply presentation/src/main/java/com/madrid/presentation/screens/detailsScreen/similarMedia/SeeAllSimilarMediaScreen.kt]: image

**Review by yasserahmed10 — APPROVED** [review]

File: presentation/src/main/java/com/madrid/presentation/screens/detailsScreen/similarMedia/SimilarMoviesScreen.kt [hunk 2]
```diff
@@ -58,7 +58,7 @@ fun SimilarMoviesSection(
                     movieImage = movie.imageUrl,
                     rate = movie.rating,
                     width = 124.dp,
-                    imageHeight = 202.dp,
+                    imageHeight = 136.dp,
```
Comment (Alaakhaled101) [inline presentation/src/main/java/com/madrid/presentation/screens/detailsScreen/similarMedia/SimilarMoviesScreen.kt]: height is 160.dp

review1

**Review by Alaakhaled101 — APPROVED** [review]
