### PR TITLE
Fix/add to favorite

### LINKED ISSUE #433: Remove from favorite for Movies and Series

### PR DESCRIPTION
**Pull request by tasneem-hakeem**
This PR provides the ability to add and remove from favorites and updates the details view models to toggle movies and series favorite state.

https://github.com/user-attachments/assets/6da609ef-de60-4602-a827-92d2bfdb54a5

### CODE REVIEW

**Comment by MostafaMohamed2002** [comment]
add video showing the feature

File: data/src/main/java/com/madrid/data/dataSource/remote/RemoteDataSourceImpl.kt [hunk 1]
```diff
@@ -305,10 +308,28 @@ class RemoteDataSourceImpl @Inject constructor(
 
     }
 
-    override suspend fun addToFavorite(
-        sessionId: String,
-        request: AddToFavoriteRequest
-    ) {
+    override suspend fun addMovieToFavorite(movieId: Int, sessionId: String, isFavorite: Boolean) {
```
Comment (ahmedhgabr) [inline data/src/main/java/com/madrid/data/dataSource/remote/RemoteDataSourceImpl.kt]: `set` instead of `add`

File: data/src/main/java/com/madrid/data/dataSource/remote/RemoteDataSourceImpl.kt [hunk 2]
```diff
@@ -305,10 +308,28 @@ class RemoteDataSourceImpl @Inject constructor(
...
+
+        val accountId = api.getAccountDetails(sessionId).id
+        api.addToFavorite(
+            accountId = accountId,
+            sessionId = sessionId,
+            body = request
+        )
+    }
+
+    override suspend fun addSeriesToFavorite(seriesId: Int, sessionId: String, isFavorite: Boolean) {
```
Comment (ahmedhgabr) [inline data/src/main/java/com/madrid/data/dataSource/remote/RemoteDataSourceImpl.kt]: same

File: data/src/main/java/com/madrid/data/repositories/MovieRepositoryImpl.kt [hunk 3]
```diff
@@ -212,19 +210,15 @@ class MovieRepositoryImpl @Inject constructor(
...
     }
 
-    override suspend fun addMovieToFavorite(mediaId: Int, sessionId: String) {
-        val request = AddToFavoriteRequest(
-            mediaType = "movie",
-            mediaId = mediaId,
-            favorite = true
-        )
-        remoteDataSource.addToFavorite(
+    override suspend fun addMovieToFavorite(movieId: Int, sessionId: String, isFavorite: Boolean) {
```
Comment (ahmedhgabr) [inline data/src/main/java/com/madrid/data/repositories/MovieRepositoryImpl.kt]: same

File: data/src/main/java/com/madrid/data/repositories/SeriesRepositoryImpl.kt [hunk 4]
```diff
@@ -109,15 +108,15 @@ class SeriesRepositoryImpl @Inject constructor(
...
     }
 
-    override suspend fun addSeriesToFavorite(mediaId: Int, sessionId: String) {
-        val request = AddToFavoriteRequest(
-            mediaType = "tv",
-            mediaId = mediaId,
-            favorite = true
-        )
-        remoteDataSource.addToFavorite(
+    override suspend fun addSeriesToFavorite(
```
Comment (ahmedhgabr) [inline data/src/main/java/com/madrid/data/repositories/SeriesRepositoryImpl.kt]: same

File: data/src/main/java/com/madrid/data/repositories/remote/RemoteDataSource.kt [hunk 5]
```diff
@@ -106,8 +104,7 @@ interface RemoteDataSource {
     suspend fun getUserRatingForSeries(sessionId: String):RatingSeriesResponse
 
     // region addToFavorite
-    suspend fun addToFavorite(sessionId: String, request: AddToFavoriteRequest)
+    suspend fun addMovieToFavorite(movieId:Int, sessionId: String, isFavorite: Boolean)
+    suspend fun addSeriesToFavorite(seriesId:Int, sessionId: String, isFavorite: Boolean)
```
Comment (ahmedhgabr) [inline data/src/main/java/com/madrid/data/repositories/remote/RemoteDataSource.kt]: .

File: domain/src/main/java/com/madrid/domain/repository/SeriesRepository.kt [hunk 6]
```diff
@@ -26,9 +25,9 @@ interface SeriesRepository {
     suspend fun getSeriesGenres(): List<Genre>
     suspend fun getSeriesByGenreId(page: Int, genreId: Int?, sortBy: SortType): List<Series>
     suspend fun addRatingSeries(seriesId: Int, rate: Double)
-    suspend fun getUserSeriesRate(sessionId:String): List<GetUserRatedSeriesUseCase.RatedSeries>
+    suspend fun getUserSeriesRate(sessionId: String): List<GetUserRatedSeriesUseCase.RatedSeries>
     suspend fun addSeriesToHistory(seriesId: Int)
     suspend fun getAllSeriesInHistory(): List<Series>
     suspend fun getFavoriteSeries(sessionId: String): List<Series>
-    suspend fun addSeriesToFavorite(mediaId:Int, sessionId: String)
+    suspend fun addSeriesToFavorite(seriesId: Int, sessionId: String, isFavorite: Boolean)
```
Comment (ahmedhgabr) [inline domain/src/main/java/com/madrid/domain/repository/SeriesRepository.kt]: .

**Review by ahmedhgabr — CHANGES_REQUESTED** [review]

File: data/src/main/java/com/madrid/data/dataSource/remote/RemoteDataSourceImpl.kt (hunk 1 above)
Comment (tasneem-hakeem) [reply data/src/main/java/com/madrid/data/dataSource/remote/RemoteDataSourceImpl.kt]: Done

**Review by ahmedhgabr — APPROVED** [review]

**Review by baraa0abd — APPROVED** [review]
