### PR TITLE
fix : artist placeOfBirth format

### LINKED ISSUE #315: fix artist placeOfBirth format

### PR DESCRIPTION
**Pull request by fatimafaisalghazi**
country2
//////
country

### CODE REVIEW

**Review by baraa0abd — APPROVED** [review]

**Review by Mohammed-qmr — APPROVED** [review]

File: data/src/main/java/com/madrid/data/dataSource/remote/mapper/ArtistMappers.kt [hunk 1]
```diff
@@ -12,7 +12,10 @@ fun ArtistDetailsResponse.toArtist(): Artist {
         name = this.name ?: "",
         role = this.role ?: "",
         dateOfBirth = this.birthDay ?: "",
-        country = this.placeOfBirth ?: "",
+        country = this.placeOfBirth!!.split(",")
```
Comment (yousef-osama11) [inline data/src/main/java/com/madrid/data/dataSource/remote/mapper/ArtistMappers.kt]: use elvis instead of not null op
