### PR TITLE
Fix/navigation to details

### LINKED ISSUE #235: 92- white screen when navigation
when navigate to actor details

https://github.com/user-attachments/assets/dc8858dc-e8bd-48bc-a2ad-2ae9e1851275

### LINKED ISSUE #236: 55- the top cast section is cut in the air in horizontal >>>>>>>>>>>>
56- similar movies also is cut in the air in horizontal 👍 
 57- the top cast name does not have overlap here and in figma have now if the name is tall it takes alot of space 👍 
 58- in see all in top cast doesn't have icon but you write "> 👍 
 59- see all in reviews does not have icon ">" 👍 

121- The description has a large padding form the start and end
122- The "See All" icon for the Current Seasons section is different
123- The "See All" icon for the Similar Series section and the review section is missing.
124- The rate element has a background that doesn’t exist in Figma, and its color is incorrect.
126- The reviews the padding between the title and the date of the review is not exists

Image

### LINKED ISSUE #250: bug : series details : review and similar series not appeare

### LINKED ISSUE #251: 32- there is no padding between actor card and his name

### LINKED ISSUE #252: 33- the actor is not clickable ( these is no actor details )

### LINKED ISSUE #254: 58- in see all in top cast doesn't have icon but you write ">" 59- see all in reviews does not have icon ">"

### LINKED ISSUE #255: 87- the "known for" is not bold and doesn't match the text size in figma 88- the movies and series in known for is not clickable i can't get to it's details
Image

### LINKED ISSUE #256: bug : feature  / similar movie screen ui
95- screen have only two column here (the phone width is smaller but in search it's three column so there's problem here) 96- the movie title starts before the profile photo (fix this could solve the above)

https://github.com/user-attachments/assets/494e98e6-3e38-4140-9bdf-ab82bd97898f

### LINKED ISSUE #267: bug/details/ fix read more in media description
Image

Image

### PR DESCRIPTION
**Pull request by fatimafaisalghazi**
handel any clickable card to make a navigation action 

When navigating to the ActorDetails screen, a white screen flashes briefly before the actual content is shown. This occurs because the data is being loaded after navigation, and there is no visual feedback during ,,
Introduced a proper LoadingScreen composable to display a full-screen loading indicator during the data-fetching phase

 refactor : Movie details to match the design in figma

### CODE REVIEW

File: presentation/src/main/java/com/madrid/presentation/component/TopCastSection.kt [hunk 1]
```diff
@@ -35,96 +28,74 @@ fun TopCastSection(
...
-                    id = "3",
-                    name = "Ian McShane",
-                    imageUrl = "https://image.tmdb.org/t/p/w500/9H7oVx4b6Z0j3EjLZN9mzcqcJjU.jpg"
-                )
-            )
-        )
-    }
-} 
\ No newline at end of file
+//@Preview(showBackground = true)
```
Comment (ahmedhgabr) [inline presentation/src/main/java/com/madrid/presentation/component/TopCastSection.kt]: Why did you comment the `Preview`?

File: presentation/src/main/java/com/madrid/presentation/component/TopCastSection.kt [hunk 2]
```diff
@@ -35,96 +28,74 @@ fun TopCastSection(
...
 @Composable
 private fun CastMemberItem(
+    onCastMemberClick: (Int) -> Unit,
     castMember: CastMember,
     modifier: Modifier = Modifier
 ) {
     Column(
         horizontalAlignment = Alignment.CenterHorizontally,
-        modifier = modifier
+        modifier = Modifier.size(height = 111.dp, width = 86.dp),
```
Comment (ahmedhgabr) [inline presentation/src/main/java/com/madrid/presentation/component/TopCastSection.kt]: Use `modifier` from the parameter

**Review by ahmedhgabr — DISMISSED** [review]

File: presentation/src/main/java/com/madrid/presentation/screens/detailsScreen/castDetails/loadingScreen.kt [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+import androidx.compose.material.CircularProgressIndicator
+import androidx.compose.runtime.Composable
+import androidx.compose.ui.Alignment
+import androidx.compose.ui.Modifier
+import androidx.compose.ui.unit.dp
+import com.madrid.designSystem.component.MovioText
+import com.madrid.designSystem.theme.Theme
+
+@Composable
+fun LoadingScreen(
```
Comment (ahmedhgabr) [inline presentation/src/main/java/com/madrid/presentation/screens/detailsScreen/castDetails/loadingScreen.kt:18]: This is so cool 👏 💯

**Review by baraa0abd — APPROVED** [review]

**Review by tasneem-hakeem — APPROVED** [review]
