### PR TITLE
fix: loading data when navigate back to library screen

### LINKED ISSUE #488: Reload Library after back from details
- Go to the library screen -> Click on any movie or series in Favorite (to open the details) -> Go back 
The History section didn't add the movie/series.

- You can also remove an item from the favorite/history, and go back. The screen will not get updated 

_You can just call the refresh function, but I don't know the suitable trigger_

### PR DESCRIPTION
**Pull request by yousef-osama11**
Done: when navigate to details from library screen , and then go back , the library screen reloads data

### CODE REVIEW

**Review by yasserahmed10 — APPROVED** [review]

File: presentation/src/main/java/com/madrid/presentation/screens/libraryScreen/LibraryScreen.kt [hunk 1]
```diff
@@ -44,6 +44,10 @@ fun LibraryScreen(
     val state = libraryViewModel.state.collectAsStateWithLifecycle().value
     val navController = LocalNavController.current
 
+    LaunchedEffect(Unit) {
```
Comment (ahmedhgabr) [inline presentation/src/main/java/com/madrid/presentation/screens/libraryScreen/LibraryScreen.kt:47]: In this case, should we change the View All Screens back button to navigateUp() ?

**Review by ahmedhgabr — APPROVED** [review]
